<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_KEDAUNG</name>
   <tag></tag>
   <elementGuidId>7e4141dd-aaf6-4fe4-97c1-2f80bb2d0c1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'KEDAUNG')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;KEDAUNG&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>94c3e814-2a69-4324-b440-0016ed017b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hierarchy</value>
      <webElementGuid>a02d5efa-b58d-449e-9b5a-0a63500414cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/h/3674061006</value>
      <webElementGuid>6ec7aa6a-93f6-4ae6-b5f4-4af775659aef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KEDAUNG</value>
      <webElementGuid>2e2a39f7-811d-4604-881d-4872a2dbfae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/div[@class=&quot;container&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container sidenav-container&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content&quot;]/app-hierarchy[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/main[@class=&quot;result ng-star-inserted&quot;]/table[@class=&quot;collapsed_border sticky_table&quot;]/tbody[@class=&quot;data&quot;]/tr[@class=&quot;ng-star-inserted&quot;]/td[1]/div[@class=&quot;lokasi&quot;]/a[@class=&quot;hierarchy&quot;]</value>
      <webElementGuid>6ce819ea-433a-4652-90d5-23040b499e64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'KEDAUNG')]</value>
      <webElementGuid>c1836adc-3851-40f8-989a-ab08d5957588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BENDA BARU'])[1]/following::a[2]</value>
      <webElementGuid>d71d37dd-be1a-4b23-b60d-1c7627d2f49c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BAMBU APUS'])[1]/following::a[5]</value>
      <webElementGuid>f6389f1f-936d-47bf-856b-358a7144750b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAMULANG BARAT'])[1]/preceding::a[2]</value>
      <webElementGuid>f94ea709-b6d8-4d51-9dca-fa9e51ec3c4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAMULANG TIMUR'])[1]/preceding::a[5]</value>
      <webElementGuid>6111e866-79a4-46ee-a3ed-b6ad14226d86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='KEDAUNG']/parent::*</value>
      <webElementGuid>7af2925f-bd70-4545-ab03-42e9435027e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/h/3674061006')]</value>
      <webElementGuid>d02484a7-a8e6-45ca-9d4b-9c50bfb39278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/a</value>
      <webElementGuid>714653ba-2a71-4543-9496-b9cd5a8c9a35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/h/3674061006' and (text() = 'KEDAUNG' or . = 'KEDAUNG')]</value>
      <webElementGuid>a8adba13-2dd0-49cd-aeb9-3061491083cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
