<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PAMULANG</name>
   <tag></tag>
   <elementGuidId>62edb20c-a34b-4751-97ff-50fbd03ce69d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'PAMULANG')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;PAMULANG&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fe5773fc-b369-4083-90f6-667b6657cce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hierarchy</value>
      <webElementGuid>b9332737-d43d-49c5-abce-df574366d8f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/h/367406</value>
      <webElementGuid>b07dc294-0871-4f58-ab44-0464954ea739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PAMULANG</value>
      <webElementGuid>508c1c6d-9d79-4f71-b1e9-4315cc5668f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/div[@class=&quot;container&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container sidenav-container&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content&quot;]/app-hierarchy[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/main[@class=&quot;result ng-star-inserted&quot;]/table[@class=&quot;collapsed_border sticky_table&quot;]/tbody[@class=&quot;data&quot;]/tr[@class=&quot;ng-star-inserted&quot;]/td[1]/div[@class=&quot;lokasi&quot;]/a[@class=&quot;hierarchy&quot;]</value>
      <webElementGuid>6b16706e-0fe2-4da7-9cb2-c8f5a0972549</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'PAMULANG')]</value>
      <webElementGuid>73350a41-2501-4a5c-987f-bd0ec5612ca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CIPUTAT TIMUR'])[1]/following::a[3]</value>
      <webElementGuid>8f1c002e-8361-46e6-9428-61e776c1920b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CIPUTAT'])[1]/following::a[6]</value>
      <webElementGuid>3b148d1b-ad20-45fa-a373-56560a72bbc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PONDOK AREN'])[1]/preceding::a[3]</value>
      <webElementGuid>f36eb450-6550-4a83-840c-a4182193ecf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SERPONG'])[1]/preceding::a[6]</value>
      <webElementGuid>9e69aad1-3709-40f3-a38e-d57eae4824c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PAMULANG']/parent::*</value>
      <webElementGuid>8bc48f8b-a8e1-4478-ab64-2127894dad50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/h/367406')]</value>
      <webElementGuid>b3ea1cc3-6bdc-4f07-9ef1-c2c6bad23f26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/a</value>
      <webElementGuid>8dffba81-c232-427f-bd11-a48acf582e76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/h/367406' and (text() = 'PAMULANG' or . = 'PAMULANG')]</value>
      <webElementGuid>2c08e77c-a72f-4f85-8aa7-a6016591641a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
