<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_BANTEN</name>
   <tag></tag>
   <elementGuidId>05d76d07-8807-4902-be70-c8c9fccfdf5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div[2]/div/div[2]/div[2]/div/div/table/tbody/tr[3]/td/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(3) > td > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;BANTEN&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>95715047-a7a7-4ab7-9f33-9cbbf3f74304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/pilpres/hitung-suara/36</value>
      <webElementGuid>43153d56-b181-4f27-b788-9b1dceacad3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BANTEN</value>
      <webElementGuid>b6fc6d74-f660-4f28-8e88-bcc340017cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;card mt-1&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;overflow-auto&quot;]/div[@class=&quot;class row mt-4&quot;]/div[@class=&quot;col-lg-12&quot;]/table[@class=&quot;table table-hover table-bordered fs-12&quot;]/tbody[1]/tr[3]/td[1]/a[1]</value>
      <webElementGuid>3c940d2b-e821-4a69-88ae-3a668e115585</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[2]/div/div[2]/div[2]/div/div/table/tbody/tr[3]/td/a</value>
      <webElementGuid>43d5122a-4255-42c5-b664-70f781e1ccff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'BANTEN')]</value>
      <webElementGuid>4df5df65-d464-49fa-9d3b-4c90b721f68c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BALI'])[1]/following::a[1]</value>
      <webElementGuid>07c824ad-b318-4b32-a4bd-c6f3abdf3d32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACEH'])[1]/following::a[2]</value>
      <webElementGuid>f4ccd845-3cdd-4110-b5c5-ec2fda1e8b98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BENGKULU'])[1]/preceding::a[1]</value>
      <webElementGuid>dabf0680-78e6-4cbb-aed7-a77e2dc2cbea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DAERAH ISTIMEWA YOGYAKARTA'])[1]/preceding::a[2]</value>
      <webElementGuid>5f7366b3-bc23-43c4-879e-39fac6961b6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BANTEN']/parent::*</value>
      <webElementGuid>a42d403c-21d9-41ff-87ef-06004075050e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/pilpres/hitung-suara/36')]</value>
      <webElementGuid>4901f479-415f-41da-9655-2c7f12be5298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/a</value>
      <webElementGuid>8e2fde31-1f13-469b-b35f-e408309af302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/pilpres/hitung-suara/36' and (text() = 'BANTEN' or . = 'BANTEN')]</value>
      <webElementGuid>02b69b54-3263-417a-879a-c291a949be55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
