<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_KEDAUNG</name>
   <tag></tag>
   <elementGuidId>ed433cd6-f0d6-4873-adfe-f2c05329d1a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div[3]/div[2]/div[2]/div[2]/div/div/table/tbody/tr[3]/td/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(3) > td > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;KEDAUNG&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e1530cfd-ac44-411d-bb98-0bf00b86d64a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/pilpres/hitung-suara/36/3674/367406/3674061006</value>
      <webElementGuid>4478ad70-3f99-4a11-91eb-0100971b2ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KEDAUNG</value>
      <webElementGuid>f59a4c97-910b-47a6-b98c-615341287d43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;overflow-auto&quot;]/div[@class=&quot;class row mt-4&quot;]/div[@class=&quot;col-lg-12&quot;]/table[@class=&quot;table table-hover table-bordered fs-12&quot;]/tbody[1]/tr[3]/td[1]/a[1]</value>
      <webElementGuid>c10a3f97-f759-4bfd-8054-6e64b09e54f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[3]/div[2]/div[2]/div[2]/div/div/table/tbody/tr[3]/td/a</value>
      <webElementGuid>fbe43ff7-d5a3-4204-8a86-bbec304c1333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'KEDAUNG')]</value>
      <webElementGuid>3ddbef46-e289-49c4-83d2-78b47cd9b1e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BENDA BARU'])[1]/following::a[1]</value>
      <webElementGuid>a54d0375-aa46-489a-a7cb-ab6c36620d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BAMBU APUS'])[1]/following::a[2]</value>
      <webElementGuid>fc060368-8a25-416c-9600-1b8a8e87c65f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAMULANG BARAT'])[1]/preceding::a[1]</value>
      <webElementGuid>2f9071bb-6a54-42fe-8347-c9b3b99c2f79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAMULANG TIMUR'])[1]/preceding::a[2]</value>
      <webElementGuid>b3286bae-d9c9-4618-861e-25006a171c12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='KEDAUNG']/parent::*</value>
      <webElementGuid>f5ba05e4-5552-4228-9f85-dc4ebf015e70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/pilpres/hitung-suara/36/3674/367406/3674061006')]</value>
      <webElementGuid>142b5c4f-9789-4c41-ad07-dc5876f4857e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/a</value>
      <webElementGuid>af1bd2d2-5e01-4f9d-966f-1f63bfcbea84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/pilpres/hitung-suara/36/3674/367406/3674061006' and (text() = 'KEDAUNG' or . = 'KEDAUNG')]</value>
      <webElementGuid>9525d9fe-de1b-4817-9ac9-2640d13d587f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
