<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PAMULANG</name>
   <tag></tag>
   <elementGuidId>5e72dc8a-9c85-4caf-9f55-502653ddfdf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div[3]/div[2]/div[2]/div[2]/div/div/table/tbody/tr[3]/td/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(3) > td > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;PAMULANG&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>446acf95-c729-457a-acac-c37541db22dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/pilpres/hitung-suara/36/3674/367406</value>
      <webElementGuid>00ecfa0b-146f-422c-b4b9-5f86a4f980a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PAMULANG</value>
      <webElementGuid>9fb92169-1119-4441-aac2-78517829f5c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;overflow-auto&quot;]/div[@class=&quot;class row mt-4&quot;]/div[@class=&quot;col-lg-12&quot;]/table[@class=&quot;table table-hover table-bordered fs-12&quot;]/tbody[1]/tr[3]/td[1]/a[1]</value>
      <webElementGuid>a42844c2-3838-4191-9d5c-c44827d38275</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[3]/div[2]/div[2]/div[2]/div/div/table/tbody/tr[3]/td/a</value>
      <webElementGuid>88f13de9-431f-48f1-8567-19f4479aa1d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'PAMULANG')]</value>
      <webElementGuid>ebb56a9a-680b-486b-a296-b364f87745ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CIPUTAT TIMUR'])[1]/following::a[1]</value>
      <webElementGuid>6d5bef4f-ceaa-428e-9e50-4ed263a5541d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CIPUTAT'])[1]/following::a[2]</value>
      <webElementGuid>9ed4f4f7-a2fb-4323-8805-9034ac1bcaf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PONDOK AREN'])[1]/preceding::a[1]</value>
      <webElementGuid>2f3f323e-bba7-4a62-9577-4acbb989a581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SERPONG'])[1]/preceding::a[2]</value>
      <webElementGuid>46dbb386-0885-40ff-b5e4-0b9bcbfe65f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PAMULANG']/parent::*</value>
      <webElementGuid>0a0a21c0-517b-4dc7-8532-d5a206a8008d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/pilpres/hitung-suara/36/3674/367406')]</value>
      <webElementGuid>86343aaf-3a19-4444-9ea7-6d96f750f888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/a</value>
      <webElementGuid>37814273-500b-4d22-a8a2-84a44d010581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/pilpres/hitung-suara/36/3674/367406' and (text() = 'PAMULANG' or . = 'PAMULANG')]</value>
      <webElementGuid>511e4ae4-dfd6-4fb4-90f5-910608b96d69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
