<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_JOIN NOW_handphone</name>
   <tag></tag>
   <elementGuidId>d2dc1752-0252-4cda-886e-fd4c866ff4dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;handphone&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='handphone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Mobile Number&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6576453d-6fda-4036-8213-31b74179d2ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>7dccceea-c183-485a-bee4-64823cd9d052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mobile Number</value>
      <webElementGuid>f92fce0c-8e6e-4506-8693-4b96a3f884e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>handphone</value>
      <webElementGuid>6c61bc55-1469-4893-a430-637890eed66c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;content&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;style_classWrapper__OCeja&quot;]/div[@class=&quot;form-wrapper&quot;]/form[1]/div[@class=&quot;form-control&quot;]/input[1]</value>
      <webElementGuid>c92560b9-de8f-47b9-94ab-628f1d33cbb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='handphone']</value>
      <webElementGuid>f31ebf0c-647e-48f6-8f0d-b5028722293b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[4]/div/div[2]/form/div[3]/input</value>
      <webElementGuid>72a7a370-8bcf-4420-8afe-79a6410cefe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>6dc7fb59-fc70-4794-9165-82c66547d6d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @placeholder = 'Mobile Number' and @name = 'handphone']</value>
      <webElementGuid>62533fe9-827c-49fb-be89-b940c42ad2c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
